### ISSUE TITLE
[Action Buttons] Add IconLink option for this

### ISSUE THREAD

**Issue by isacoder** [future-standard/scorer-ui-kit#211]
### Description

Potentially ActionButton can send a way to handle the links  externally but since we have react-router integration in the UI Kit we can without problem add the option to send a text link instead of a onClick action to send to a different page without extra code.

**Comment by atomworks** [comment]
We use action buttons for launching external pages like Edge UIs but I don't think we've ever used a button to launch a page internally within a project like this. I think because of the way we treat those moments separately, it's not something we need to worry about unless if specifically comes up in the future, so I'll close this one up if you don't mind.
